name: Build, sign and release
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  release:
    name: "Build, sign and release kubectl"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Find latest kubectl version
        run: |
          KUBECTL_VER="$(curl https://storage.googleapis.com/kubernetes-release/release/stable-1.31.txt)"
          echo "kubectl_ver=${KUBECTL_VER}" >> $GITHUB_ENV
      - run: echo "kubectl binary is at version ${{ env.kubectl_ver }}"
      - name: Stop if ${{ github.repository_owner }}/kubectl:${{ env.kubectl_ver }} in repo already
        id: check-in-repo
        run: |
          # fake no-op token, image is public
          TOKEN=$(curl https://ghcr.io/token\?scope\="repository:${{ github.repository_owner }}/kubectl:pull" | jq .token | tr -d \")
          if curl -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/${{ github.repository_owner }}/kubectl/tags/list \
               | grep \"${{ env.kubectl_ver }}\";
          then
              echo "${{ github.repository_owner }}/kubectl:${{ env.kubectl_ver }} is in repo already"
              echo "image-exists=true" >> $GITHUB_ENV
          fi
      - uses: sigstore/cosign-installer@fb28c2b6339dcd94da6e4cbcbc5e888961f6f8c3 # v3.9.0
        if: env.image-exists != 'true'
      - name: Checkout code
        if: env.image-exists != 'true'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download and verify kubectl
        if: env.image-exists != 'true'
        run: ./download-kubectl.sh ${{ env.kubectl_ver }}
      - name: Set up QEMU
        if: env.image-exists != 'true'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        if: env.image-exists != 'true'
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Login to GitHub Container Registry
        if: env.image-exists != 'true'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push tagged container image
        id: build-image
        if: env.image-exists != 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kubectl:${{ env.kubectl_ver }}
      - name: Sign the image
        if: env.image-exists != 'true'
        run: |
          cosign sign --yes \
            ghcr.io/${{ github.repository_owner }}/kubectl@${{ steps.build-image.outputs.digest }}
